// sidebars.js — Sidebar configuration for Engineering Notebook
// WHY: autogenerated sidebars read the _category_.json files and doc frontmatter
// to build a fully automatic, alphabetically sorted navigation tree.
// Manual override is possible per section when ordering matters.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  notesSidebar: [
    // ── Introduction / Home ────────────────────────────────────────────────
    {
      type:  'doc',
      id:    'intro',
      label: '🏠 Start Here',
    },

    // ── Mathematics ────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '📐 Mathematics',
      link: {
        type: 'doc',
        id:   'mathematics/intro',
      },
      items: [
        'mathematics/linear-algebra-fundamentals',
      ],
    },

    // ── Operating Systems ─────────────────────────────────────────────────
    {
      type:      'category',
      label:     '⚙️ Operating Systems',
      link: {
        type: 'doc',
        id:   'operating-systems/intro',
      },
      items: [
        'operating-systems/process-management',
      ],
    },

    // ── Machine Learning ──────────────────────────────────────────────────
    {
      type:      'category',
      label:     '🧠 Machine Learning',
      link: {
        type: 'doc',
        id:   'machine-learning/intro',
      },
      items: [
        'machine-learning/gradient-descent',
      ],
    },

    // ── Java ──────────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '☕ Java',
      link: {
        type: 'doc',
        id:   'java/intro',
      },
      items: [
        'java/concurrency-basics',
      ],
    },

    // ── Systems Programming ───────────────────────────────────────────────
    {
      type:      'category',
      label:     '🔧 Systems Programming',
      link: {
        type: 'doc',
        id:   'systems-programming/intro',
      },
      items: [],
    },

    // ── Linux ─────────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '🐧 Linux',
      link: {
        type: 'doc',
        id:   'linux/intro',
      },
      items: [],
    },
  ],
};

export default sidebars;
