// sidebars.js — Sidebar configuration for Engineering Notebook
// WHY: autogenerated sidebars read the _category_.json files and doc frontmatter
// to build a fully automatic, alphabetically sorted navigation tree.
// Manual override is possible per section when ordering matters.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  notesSidebar: [
    // ── Introduction / Home ────────────────────────────────────────────────
    {
      type:  'doc',
      id:    'intro',
      label: '🏠 Start Here',
    },

    // ── Mathematics ────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '📐 Mathematics',
      link: {
        type: 'doc',
        id:   'mathematics/intro',
      },
      items: [
        'mathematics/linear-algebra-fundamentals',
        'mathematics/calculus-derivatives',
        'mathematics/probability-foundations',
        'mathematics/discrete-math-intro',
      ],
    },

    // ── Operating Systems ─────────────────────────────────────────────────
    {
      type:      'category',
      label:     '⚙️ Operating Systems',
      link: {
        type: 'doc',
        id:   'operating-systems/intro',
      },
      items: [
        'operating-systems/process-management',
        'operating-systems/memory-management',
        'operating-systems/file-systems',
        'operating-systems/scheduling-algorithms',
        'operating-systems/concurrency-deadlocks',
      ],
    },

    // ── Machine Learning ──────────────────────────────────────────────────
    {
      type:      'category',
      label:     '🧠 Machine Learning',
      link: {
        type: 'doc',
        id:   'machine-learning/intro',
      },
      items: [
        'machine-learning/gradient-descent',
        'machine-learning/linear-regression',
        'machine-learning/neural-networks-basics',
        'machine-learning/backpropagation',
        'machine-learning/regularization',
      ],
    },

    // ── Java ──────────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '☕ Java',
      link: {
        type: 'doc',
        id:   'java/intro',
      },
      items: [
        'java/concurrency-basics',
        'java/jvm-internals',
        'java/collections-framework',
        'java/generics-deep-dive',
        'java/streams-functional',
      ],
    },

    // ── Systems Programming ───────────────────────────────────────────────
    {
      type:      'category',
      label:     '🔧 Systems Programming',
      link: {
        type: 'doc',
        id:   'systems-programming/intro',
      },
      items: [
        'systems-programming/memory-layout',
        'systems-programming/pointers-and-references',
        'systems-programming/system-calls',
      ],
    },

    // ── Linux ─────────────────────────────────────────────────────────────
    {
      type:      'category',
      label:     '🐧 Linux',
      link: {
        type: 'doc',
        id:   'linux/intro',
      },
      items: [
        'linux/filesystem-hierarchy',
        'linux/shell-scripting',
        'linux/process-management',
        'linux/networking-commands',
      ],
    },
  ],
};

export default sidebars;
